# .github/workflows/ci.yml
name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync environment
        run: uv sync

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Format check (black)
        run: uv run black --check .

      - name: Tests (pytest)
        run: uv run pytest -q

